### ISSUE TITLE
BUG - Compiler complains about missing  ';'

### ISSUE THREAD

**Issue by szydek** [okyeron/OMX-27#10]
Env setup: using Teensyduino v1.53 to compile

First attempt compiling the latest main (OMX_VERSION = 1.1.0), I get an error about missing ";" for these "const int" lines:

https://github.com/okyeron/OMX-27/blob/94ae607654fbebe0e85c6e9f00224fd4771debda/config.h#L49-L51

I updated to the following which appeared to fix the issue:

```#elif MIDIONLY
	const int analogPins[] = {23,A10,21,20,16};  // on MIDI only boards
#else
	const int analogPins[] = {A10,22,21,20,16}; // on 1.0
#endif
```

I can raise a bugfix PR if someone else can verify the issue as well.

**Comment by okyeron** [comment]
fixed in 95d4894d7ad085357656951fb42195b2ef7240f1
