### ISSUE TITLE
Notes not showing up in Step Record mode in S1/S2

### ISSUE THREAD

**Issue by mrmattallison** [okyeron/OMX-27#48]
Red position marker can get stuck and drawn twice. Notes are not showing up in Step Record in "Note Select Mode", they light up when pressed, but changes are not persistent on exit out of "Note Select Mode" and reentry.

**Comment by okyeron** [comment]
Can you give me a set of commands to try and replicate?

In testing just now I see the note values I entered in Step Record showing up in Note Select (so it seems persistent to me)

There is something funny with Position marker - it's off by one. Sometimes seeing single key staying red when entering Step Record.

Will investigate

**Comment by Quixotic7** [comment]
This should be fixed in grids-mode branch.

**Comment by okyeron** [comment]
Is this still active?

Can we close?
