### ISSUE TITLE
Erratic potentiometer functionality in EL - Euclidean Sequencer script

### ISSUE THREAD

**Issue by mrglennjones** [okyeron/OMX-27#55]
on the T4 version, When using the realtime editor functions on the EL - Euclidean Sequencer script. each of the potentiometers functionality is lagged and erratic and the visual display of the euclidean steps are b0rked.

https://discord.com/channels/807359285805711431/1072228285666304031/1100383674987450488

when editing the scripts parameter values, the pots work as expected. it just the realtime editor function on the far left that isn't working correctly.

https://github.com/okyeron/OMX-27/assets/78789353/d141d707-3145-4d02-9130-2c951d48465c

**Comment by kolyan94** [comment]
https://github.com/okyeron/OMX-27/assets/20342067/bf388252-74a5-4c45-b96f-e90c2b56d958

Have a similar issue with the GR mode as well. But the behaviour is a bit different: to make it usable u need just to spin it really fast. After this small preparation everything works

**Comment by mrglennjones** [comment]
> IMG_2239_480.mov
> 
> Have a similar issue with the GR mode as well. But the behaviour is a bit different: to make it usable u need just to spin it really fast. After this small preparation everything works

Yes, mine does this too..  I gather yours is the Teensy 4 too?

This looks like a similar issue to the EL one

**Comment by kolyan94** [comment]
Fixed in https://github.com/okyeron/OMX-27/pull/56

**Comment by mrglennjones** [comment]
> Fixed in #56

I owe u a pint, thanks so much :)
