### ISSUE TITLE
bug with the saves in 'Chord Mode'.

### ISSUE THREAD

**Issue by jr0dsgarage** [okyeron/OMX-27#61]
From Enduss on discord:

> Selected 'Save Slot 1', used the first 4 keys from the left for 'Custom Chords', then saved in 'Save Slot 1'.  Then loaded 'Save Slot 2' to start from scratch, created 4 new 'Custom Chords', again, using the first 4 keys from the left.  Then saved in 'Save Slot 2'.
> 
> Now, when I load 'Save Slot 1', the root note, and key octave is how I saved it, but the '+' and '-' notes of the custom chords are how I set them in 'Save Slot 2'.  Never noticed this before, 'cause with each FW update, saves were erased.
> Also, changes I make to the custom chord '+ -' notes in 'Save Slot 1', will show in 'Save Slot 2'.

**Comment by okyeron** [comment]
Whats the status on this with most recent merges?

**Comment by jr0dsgarage** [comment]
I believe this can be closed.
