### ISSUE TITLE
How to use PCB designs to order from another manufacturer?

### ISSUE THREAD

**Issue by michinger** [okyeron/OMX-27#63]
I am really exited about this project so I am trying to assemble all the parts myself because the kit is out of stock online + shipping to Europe is costly.

I am pretty inexperienced with electronics so I can't quite figure out how I could order your PCBs via an online manufacturer. I found the .ai files in the plates directory but it seems like the websites that let you upload PCB designs that I found only accept eagle, kicad or  gerber files.

Could you maybe help me out how i could best get my hands on a PCB with the provided files in the repo?

Appreciate the amazing work!

**Comment by okyeron** [comment]
The PCB design is not open source or available to be manufactured

**Comment by michinger** [comment]
Thanks for clarifying, I guess I've got to spend the extra bucks in that case. :)
